server:
  port: 9090

spring:
  datasource:
    url: ENC(P0hWFxFlQCiTdY3Zz9/4He/ZyluFzAHM468Zy2gZGKEohPukae6aUa8xVNzqQAfXTin+VVN2sRihNnnM/itbhWJaKiCKKRMd)
    username: ENC(aKFDTm4eQy7AXTjHDf9bPydXpqfW26oS)
    password: ENC(RG/4PP+JJ1IQRn06n/8Iaw==)
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 500

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(fA37MaFgT+8VvCowruiSPwsZNF6S/nRwuXKWvxkYYf1U22Zbl3JoKt3YJT6e6NsJvzcn5F7a4I/tZpuCiN13V6EKcHd7DeVnCvqAYSPRuAnWCx1CV8xdaw==)
            client-secret: ENC(bgY1FehS7RXZtjCysSCVQQYRLwbyZJLj5Tfx5IOjM7QVG19MD/Z+aulQ00S1b9ON)
            scope:
              - email
              - profile
          naver:
            client-id: ENC(P0hh74ZFFc0V3rzvBdfaYmmCj7mZDePCr6EgfILueA4=)
            client-secret: ENC(1LgrIbjZqjmbwcDAUWep2Ss3EQhnL/QA)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver
          kakao:
            client-id: ENC(XHBQGl9HB1WbNXWeaDz8Ru+tGoWlf0bUk0HWROZTo9pN2ye+Wi/STHcfin2tBtmM)
            client-secret: ENC(bWw2IEy/iQGNWW/imxVU+R62ppo6WEqBr6FXVngJUAEvP7PONnwkL8375B93616J)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

app:
  auth:
    tokenSecret: ENC(7To1Fbo1UpwEobXPhG5RR7DqfgVXotb/ovlPZFC0S6iuJaODA78HEr5u/r6g0cNnriz9nHCDqpw=)
    accessTokenExpiration: 7200
    refreshTokenExpiration: 86400

  oauth2:
    authorizedRedirectUris:
      - http://localhost:9090/
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

logging:
  level:
    root: INFO
    com.smsoft.com.smsoft.sociallogintemplate: DEBUG
    org.springframework.security: DEBUG
